import React from 'react'
import styled from 'styled-components';

const Loading = styled.div`
text-align: center;
@keyframes ldio-e8o9jfk7i8 {
  0% {
    opacity: 1;
    backface-visibility: hidden;
    transform: translateZ(0) scale(1.5,1.5);
  } 100% {
    opacity: 0;
    backface-visibility: hidden;
    transform: translateZ(0) scale(1,1);
  }
}
.ldio-e8o9jfk7i8 div > div {
  position: absolute;
  width: 20px;
  height: 20px;
  border-radius: 50%;
  background: #30c0bd;
  animation: ldio-e8o9jfk7i8 1s linear infinite;
}.ldio-e8o9jfk7i8 div:nth-child(1) > div {
  left: 136px;
  top: 90px;
  animation-delay: -0.875s;
}
.ldio-e8o9jfk7i8 > div:nth-child(1) {
  transform: rotate(0deg);
  transform-origin: 146px 100px;
}.ldio-e8o9jfk7i8 div:nth-child(2) > div {
  left: 123px;
  top: 123px;
  animation-delay: -0.75s;
}
.ldio-e8o9jfk7i8 > div:nth-child(2) {
  transform: rotate(45deg);
  transform-origin: 133px 133px;
}.ldio-e8o9jfk7i8 div:nth-child(3) > div {
  left: 90px;
  top: 136px;
  animation-delay: -0.625s;
}
.ldio-e8o9jfk7i8 > div:nth-child(3) {
  transform: rotate(90deg);
  transform-origin: 100px 146px;
}.ldio-e8o9jfk7i8 div:nth-child(4) > div {
  left: 57px;
  top: 123px;
  animation-delay: -0.5s;
}
.ldio-e8o9jfk7i8 > div:nth-child(4) {
  transform: rotate(135deg);
  transform-origin: 67px 133px;
}.ldio-e8o9jfk7i8 div:nth-child(5) > div {
  left: 44px;
  top: 90px;
  animation-delay: -0.375s;
}
.ldio-e8o9jfk7i8 > div:nth-child(5) {
  transform: rotate(180deg);
  transform-origin: 54px 100px;
}.ldio-e8o9jfk7i8 div:nth-child(6) > div {
  left: 57px;
  top: 57px;
  animation-delay: -0.25s;
}
.ldio-e8o9jfk7i8 > div:nth-child(6) {
  transform: rotate(225deg);
  transform-origin: 67px 67px;
}.ldio-e8o9jfk7i8 div:nth-child(7) > div {
  left: 90px;
  top: 44px;
  animation-delay: -0.125s;
}
.ldio-e8o9jfk7i8 > div:nth-child(7) {
  transform: rotate(270deg);
  transform-origin: 100px 54px;
}.ldio-e8o9jfk7i8 div:nth-child(8) > div {
  left: 123px;
  top: 57px;
  animation-delay: 0s;
}
.ldio-e8o9jfk7i8 > div:nth-child(8) {
  transform: rotate(315deg);
  transform-origin: 133px 67px;
}
.loadingio-spinner-spin-p7i9llod48 {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-e8o9jfk7i8 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-e8o9jfk7i8 div { box-sizing: content-box; }
/* generated by https://loading.io/ */

`;
export const Loader = () => {
	return (
		<div>
			<Loading>
				<div className="loadingio-spinner-spin-p7i9llod48"><div className="ldio-e8o9jfk7i8">
					<div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div>
				</div></div>

			</Loading>
		</div>
	)
}
