
export const SEARCH_IMAGE = 'SEARCH/SEARCH_IMAGE';

export const LIKE_IMAGE = 'USER/LIKE_IMAGE';
export const UNLIKE_IMAGE = 'USER/UNLIKE_IMAGE';
export const CHANGE_LIKE = 'USER/CHANGE_LIKE';
export const CHANGE_TOTAL_LIKE = 'USER/CHANGE_TOTAL_LIKE';
export const LOAD_USER_PROFILE = 'USER/LOAD_USER_PROFILE';


export const IMAGES_LOAD = 'IMAGE/IMAGES_LOAD';
export const CHANGE_IMAGES_STATE = 'IMAGE/CHANGE_IMAGES_STATE';
export const CHANGE_CURRENT_PAGE = 'IMAGE/CHANGE_CURRENT_PAGE';
export const RESET_SEARCH_IMAGE = 'IMAGE/RESET_SEARCH_IMAGE';
export const IS_SEARCHING = 'IMAGE/IS_SEARCHING';
export const CHANGE_SEARCH_TEXT = 'IMAGE/CHANGE_SEARCH_TEXT';
export const RESET_SEARCH_PAGE = 'IMAGE/RESET_SEARCH_PAGE';

export const LOADER_DISPLAY_ON = 'APP/LOADER_DISPLAY_ON';
export const LOADER_DISPLAY_OFF = 'APP/LOADER_DISPLAY_OFF';
export const ERROR_DISPLAY_ON = 'APP/ERROR_DISPLAY_ON';
export const ERROR_DISPLAY_OFF = 'APP/ERROR_DISPLAY_OFF';

export const ADD_TOKEN = 'AUTH/ADD_TOKEN';
export const DELETE_TOKEN = 'AUTH/DELETE_TOKEN';

export const MODAL_OPEN = 'MODAL/MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL/MODAL_CLOSE';
// export const COMMENT_CREATE = 'COMMENT/COMMENT_CREATE';
// export const COMMENT_UPDATE = 'COMMENT/COMMENT_UPDATE';
// export const COMMENT_DELETE = 'COMMENT/COMMENT_DELETE';
