
export const SEARCH_IMAGE = 'SEARCH/SEARCH_IMAGE';
export const LIKE_IMAGE = 'SEARCH/LIKE_IMAGE';
export const IMAGES_LOAD = 'IMAGE/IMAGES_LOAD';

export const LOADER_DISPLAY_ON = 'APP/LOADER_DISPLAY_ON';
export const LOADER_DISPLAY_OFF = 'APP/LOADER_DISPLAY_OFF';

export const ERROR_DISPLAY_ON = 'APP/ERROR_DISPLAY_ON';
export const ERROR_DISPLAY_OFF = 'APP/ERROR_DISPLAY_OFF';

// export const COMMENT_CREATE = 'COMMENT/COMMENT_CREATE';
// export const COMMENT_UPDATE = 'COMMENT/COMMENT_UPDATE';
// export const COMMENT_DELETE = 'COMMENT/COMMENT_DELETE';
